"""fix typing in candidate model

Revision ID: 1c8ce3a6192d
Revises: a1775142d69b
Create Date: 2023-08-02 15:38:29.406660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8ce3a6192d'
down_revision = 'a1775142d69b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
