"""Add submitted_datetime column

Revision ID: 412e5cef93eb
Revises: 1c8ce3a6192d
Create Date: 2023-08-02 15:58:04.598554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '412e5cef93eb'
down_revision = '1c8ce3a6192d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('submitted_datetime', sa.DateTime(), nullable=True))
    op.drop_column('candidate', 'submited_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('submited_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('candidate', 'submitted_datetime')
    # ### end Alembic commands ###
