"""update candidate, add cv_json column

Revision ID: 477d266d82eb
Revises: 412e5cef93eb
Create Date: 2023-08-03 10:51:33.573890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477d266d82eb'
down_revision = '412e5cef93eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('cv_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'cv_json')
    # ### end Alembic commands ###
