"""up cv_score to float

Revision ID: 93fd5440986c
Revises: 477d266d82eb
Create Date: 2023-08-04 17:13:13.688965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fd5440986c'
down_revision = '477d266d82eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
